
version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
 build:
   executor: android/android

   steps:
     - checkout
     - run:
         command: ./gradlew build
     - run:
          name: Run Tests
          command: ./gradlew lint test
     - store_test_results:
          path: app/build/test-results    